version: "3.9"

services:
  server:
    build: ./backend
    container_name: express-server
    ports:
      - "4000:3000"  
    env_file:
      - ./backend/.env
    restart: unless-stopped

  client:
    build: ./frontend
    container_name: react-client
    ports:
      - "5174:5174"  
    depends_on:
      - server
    restart: unless-stopped
